services:
  - type: web
    name: cr-d-music
    runtime: image
    repo: https://github.com/kingali371/musicsy
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: API_ID
        description: "Get this value from https://my.telegram.org/apps"
        sync: false
      - key: API_HASH
        description: "Get this value from https://my.telegram.org/apps"
        sync: false
      - key: BOT_TOKEN
        description: "Your bot token from @BotFather"
        sync: false
      - key: MONGO_DB_URI
        description: "MongoDB connection URI"
        value: mongodb+srv://zzboss:zzboss@cluster0.heabj.mongodb.net/vambir_bot?retryWrites=true&w=majority
      - key: MUSIC_BOT_NAME
        description: "Name of your music bot"
        value: "cr ダ ᴍᴜsɪᴄ"
      - key: OWNER_ID
        description: "Your Telegram user ID"
        sync: false
      - key: STRING_SESSION
        description: "Pyrogram string session for assistant account"
        sync: false
      - key: LOG_GROUP_ID
        description: "Group ID for bot logs (bot must be admin)"
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
